package com.medx.gateway.constants;

public final class HeaderConstants {

    private HeaderConstants() {
    }

    // Gateway source identification
    // Downstream services can reject calls that don't have this header (direct bypass protection)
    public static final String GATEWAY_SOURCE_HEADER = "X-Gateway-Source";
    public static final String GATEWAY_SOURCE_VALUE = "api-gateway";

    // Distributed tracing — propagated across all services
    // Generated by gateway if client doesn't provide one
    public static final String CORRELATION_ID_HEADER = "X-Correlation-Id";

    // Original request path — used in FallbackController to show real path not /fallback/*
    public static final String FORWARDED_PATH_HEADER = "X-Forwarded-Path";

    // Request entry timestamp (epoch ms) — used for end-to-end latency measurement
    public static final String REQUEST_TIME_HEADER = "X-Request-Time";

    // JWT enrichment headers — set by JwtAuthenticationFilter after token validation
    // Downstream services trust these headers; they never parse JWT themselves
    public static final String USER_ID_HEADER = "X-User-Id";
    public static final String USER_ROLE_HEADER = "X-User-Role";
    public static final String USER_EMAIL_HEADER = "X-User-Email";
}